import type { Part, BuildResult } from "./types"

const PCPARTPICKER_BASE = "https://pcpartpicker.com"

export function buildPartSearchUrl(partName: string): string {
  const encoded = encodeURIComponent(partName)
  return `${PCPARTPICKER_BASE}/search/?q=${encoded}`
}

export function buildCategorySearchUrl(category: string, partName: string): string {
  const categorySlug = category.toLowerCase().replace(/[^a-z0-9]/g, "-")
  const encoded = encodeURIComponent(partName)
  return `${PCPARTPICKER_BASE}/products/${categorySlug}/#search=${encoded}`
}

export function buildPCPartPickerUrls(part: Part): Part {
  return {
    ...part,
    pcpartpickerSearchUrl: buildPartSearchUrl(part.name),
  }
}

export function generateBuildListText(build: BuildResult): string {
  const lines = build.parts.map(
    (part, i) =>
      `${i + 1}. ${part.category}: ${part.name} — $${part.price.toFixed(2)}`
  )

  return [
    "=== AI PC Builder — Parts List ===",
    "",
    ...lines,
    "",
    `Total: $${build.totalPrice.toFixed(2)}`,
    "",
    "=== Build Summary ===",
    build.summary,
    "",
    "=== Estimated Performance ===",
    build.estimatedPerformance,
    "",
    "=== Upgrade Path ===",
    ...build.upgradePath.map((u) => `- ${u}`),
    "",
    "To enter this build on PCPartPicker:",
    "1. Go to https://pcpartpicker.com/list/",
    "2. Click 'Create a New List'",
    "3. Add each part manually using the search function",
    "",
    "Generated by AI PC Builder",
  ].join("\n")
}
