import jsPDF from "jspdf"
import type { BuildResult } from "./types"

export function generateBuildPDF(build: BuildResult): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  function addLine(text: string, fontSize = 10, indent = 0) {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    doc.setFontSize(fontSize)
    doc.text(text, 15 + indent, y)
    y += fontSize * 0.35 + 2
  }

  function addDivider() {
    if (y > 265) {
      doc.addPage()
      y = 20
    }
    doc.setDrawColor(100, 100, 100)
    doc.line(15, y, pageWidth - 15, y)
    y += 6
  }

  doc.setFont("helvetica", "bold")
  doc.setFontSize(22)
  doc.setTextColor(6, 182, 212)
  doc.text("AI PC Builder — Build Report", 15, y)
  y += 12

  doc.setFont("helvetica", "normal")
  doc.setFontSize(11)
  doc.setTextColor(200, 200, 200)
  doc.text(`Generated by AI PC Builder`, 15, y)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 15, y, { align: "right" })
  y += 10

  addDivider()

  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.setTextColor(255, 255, 255)
  doc.text(`Build Summary`, 15, y)
  y += 8

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(200, 200, 200)
  addLine(build.summary)

  y += 2
  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.setTextColor(6, 182, 212)
  addLine(`Total: ${build.currency} ${build.totalPrice.toFixed(2)}`)
  addLine(`Estimated Performance: ${build.estimatedPerformance}`)
  addLine(`Estimated Power Draw: ${build.totalWattage}W`)

  addDivider()

  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.setTextColor(255, 255, 255)
  doc.text(`Parts List`, 15, y)
  y += 8

  for (let i = 0; i < build.parts.length; i++) {
    const part = build.parts[i]

    if (y > 240) {
      doc.addPage()
      y = 20
    }

    doc.setFont("helvetica", "bold")
    doc.setFontSize(11)
    doc.setTextColor(6, 182, 212)
    doc.text(`${part.category}`, 15, y)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    doc.setTextColor(255, 255, 255)
    doc.text(`${part.name}`, 50, y)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(168, 85, 247)
    doc.text(`${part.currency} ${part.price.toFixed(2)}`, pageWidth - 15, y, { align: "right" })
    y += 5

    doc.setFont("helvetica", "normal")
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    const reasonLines = doc.splitTextToSize(part.reason, pageWidth - 30)
    for (const line of reasonLines) {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(line, 15, y)
      y += 4
    }
    y += 3
  }

  addDivider()

  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.setTextColor(255, 255, 255)
  doc.text(`Build Philosophy`, 15, y)
  y += 8
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(200, 200, 200)
  const explanationLines = doc.splitTextToSize(build.buildExplanation, pageWidth - 30)
  for (const line of explanationLines) {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    doc.text(line, 15, y)
    y += 5
  }

  addDivider()

  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.setTextColor(255, 255, 255)
  doc.text(`Upgrade Path`, 15, y)
  y += 8
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(200, 200, 200)
  for (const upgrade of build.upgradePath) {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    doc.text(`- ${upgrade}`, 15, y)
    y += 6
  }

  addDivider()

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text(
    "PCPartPicker Compatibility: To verify this build, visit https://pcpartpicker.com/list/ and enter the parts manually.",
    15,
    y
  )
  y += 4
  doc.text("Prices are estimates and may vary. Always check current pricing before purchasing.", 15, y)
  y += 4
  doc.text(`Generated by AI PC Builder — ${new Date().toISOString()}`, 15, y)

  return doc
}
